/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#5b0017',
        'surface-container-high': '#28283d',
        'secondary': '#66dca9',
        'on-tertiary-container': '#00311c',
        'inverse-primary': '#b71d3f',
        'surface-container': '#1e1e32',
        'surface-container-lowest': '#0c0c1f',
        'on-tertiary': '#003921',
        'error-container': '#93000a',
        'surface-dim': '#111125',
        'secondary-fixed': '#84f8c4',
        'tertiary-container': '#25a46d',
        'surface-container-low': '#1a1a2e',
        'on-error': '#690005',
        'primary-container': '#fc536d',
        'tertiary-fixed': '#84f9ba',
        'secondary-container': '#22a476',
        'tertiary-fixed-dim': '#67dc9f',
        'tertiary': '#67dc9f',
        'error': '#ffb4ab',
        'on-secondary': '#003825',
        'outline': '#a9898a',
        'on-primary': '#67001c',
        'surface-tint': '#ffb2b7',
        'primary-fixed-dim': '#ffb2b7',
        'secondary-fixed-dim': '#66dca9',
        'on-secondary-fixed': '#002114',
        'on-tertiary-fixed-variant': '#005232',
        'inverse-surface': '#e2e0fc',
        'on-background': '#e2e0fc',
        'surface-container-highest': '#333348',
        'on-secondary-fixed-variant': '#005138',
        'background': '#111125',
        'surface': '#111125',
        'primary': '#ffb2b7',
        'on-error-container': '#ffdad6',
        'surface-variant': '#333348',
        'primary-fixed': '#ffdadb',
        'outline-variant': '#5a4042',
        'inverse-on-surface': '#2f2e43',
        'surface-bright': '#37374d',
        'on-secondary-container': '#003120',
        'on-tertiary-fixed': '#002111',
        'on-surface': '#e2e0fc',
        'on-primary-fixed': '#40000e',
        'on-surface-variant': '#e2bebf',
        'on-primary-fixed-variant': '#91002b',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
